
import React from 'react';

export type Status = 'Pendente' | 'Em andamento' | 'Concluída';
export type View = 'dashboard' | 'calendar' | 'list' | 'reports' | 'reminders' | 'profile' | 'taskDetail' | 'projects' | 'projectDetail' | 'settings';

export interface Tag {
  id: string;
  name: string;
  color: string;
  bgColor: string;
  baseColor: 'red' | 'yellow' | 'green' | 'blue' | 'indigo' | 'purple' | 'pink';
}

export interface Category {
  id:string;
  name: string;
  color: 'blue' | 'purple' | 'yellow' | 'red' | 'green' | 'gray';
  icon: React.FC<{ className?: string }>;
}

export interface SubTask {
  id: string;
  text: string;
  completed: boolean;
  note?: string;
}

export interface Activity {
  id: string;
  type: 'status_change' | 'note' | 'creation' | 'reminder' | 'property_change' | 'task_update' | 'project';
  timestamp: string; // When the event happened (e.g., reminder was set)
  
  // Common
  user?: string; 
  isAiGenerated?: boolean; // Flag to indicate if the activity was generated by AI
  
  // For context in project view
  taskTitle?: string;

  // For project activities
  action?: 'added' | 'removed' | 'changed';
  projectName?: string; // Used when logging inside a task to know which project was involved

  // For status_change
  from?: Status | string; // Relaxed type to allow string for generic changes if needed, though Status is preferred
  to?: Status | string;
  
  // For note & reminder message
  note?: string;

  // For reminder
  notifyAt?: string; // The time the notification should trigger

  // For property_change
  property?: 'Categoria' | 'Prioridade' | 'Título' | 'Prazo Final' | 'Projeto';
  oldValue?: string;
  newValue?: string;

  // For bulk actions (aggregated log)
  affectedTasks?: string[];
  count?: number;
}

export interface Notification {
  id: string; // e.g., 'task-1-overdue', 'reminder-123'
  taskId: string;
  taskTitle: string;
  message: string;
  notifyAt: string; // The original due date or reminder time
}

export interface NotificationSettings {
  enabled: boolean;
  remindDaysBefore: number;
  taskReminders: boolean; // New
  habitReminders: boolean; // New
  marketingEmails: boolean; // New
}

export interface AppSettings {
  disableOverdueColor: boolean;
  timeFormat: '12h' | '24h'; // New
  weekStart: 'sunday' | 'monday'; // New
  enableAi: boolean; // New
  enableAnimations: boolean; // New
}

export interface Task {
  id:string;
  title: string;
  description?: string;
  dateTime: string;
  dueDate?: string;
  categoryId: string;
  tagId: string;
  status: Status;
  subTasks: SubTask[];
  activity: Activity[];
  tags?: string[];
  projectId?: string;
}

export interface ConfirmationToastData {
  id: number;
  title: string;
  subtitle?: string;
  type: 'success' | 'error';
}

export interface Habit {
  id: string;
  title: string;
  // 'auto-task-completion': checks if at least one task was completed today.
  // 'manual': user checks it off manually.
  type: 'auto-task-completion' | 'manual';
  reminderTime?: string; // e.g., "09:00"
  lastCompletedDate?: string; // ISO date string 'YYYY-MM-DD'
  overrideDate?: string; // ISO date string 'YYYY-MM-DD' to mark an auto-habit as uncompleted for a day
}

export interface HabitTemplate {
    id: string;
    title: string;
    type: Habit['type'];
    description: string;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  color: string;
  icon?: string; // 'folder' | 'rocket' | 'code' | 'globe' | 'star' | 'heart' | 'chart'
  createdAt: string;
  activity: Activity[];
}

export type PeriodOption = 'last-week' | 'last-month' | 'last-semester' | 'current-year' | 'last-year' | 'custom';
export type SummaryType = 'self-review' | 'highlights' | 'learnings' | 'objective' | 'timeline';
export type Tone = 'professional' | 'neutral' | 'human' | 'direct';
export type Length = 'short' | 'medium' | 'detailed';
export type Focus = 'deliverables' | 'impact' | 'learning' | 'balance';

export interface SavedSummary {
    id: string;
    date: string;
    title: string;
    content: string;
    config: {
        type: SummaryType;
        period: PeriodOption;
    };
}
